version: '4'
services:
  db:
    image: postgres:14.2-alpine3.15
    restart: always
    ports:
      - '8009:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespostgres}
      POSTGRES_DB: postgres
